name: Build Gitbook Doc

on:
  push:
    branches:
      - master

jobs:
  build_doc:
    name: Build doc
    runs-on: ubuntu-18.04
    steps:
      - name: build doc by gitbook
        uses: zanderzhao/gitbook-action@v1.2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          time_zone: Asia/Shanghai
          source_branch: master             # clone source master
          source_dir: docs                  # gitbook-sorce at dir:docs
          publish_dir: _book            # publish for this repo dir:gitbook-docs
          publish_branch: doc